# Generated by Django 3.0.5 on 2020-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=None)),
                ('country', models.CharField(default='UNK', max_length=2)),
            ],
        ),
    ]
