# Generated by Django 3.0.5 on 2020-04-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard_api', '0002_auto_20200420_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSubmitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_rank', models.IntegerField()),
                ('max_rank', models.IntegerField()),
            ],
        ),
    ]
